CREATE TABLE IF NOT EXISTS `admins` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `aypwips` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `string` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) DEFAULT CHARSET=utf8;

INSERT INTO `aypwips` (`id`, `string`) VALUES
(1, 'Sure, %s, but how are we going to find chaps our size?'),
(2, 'I think so, %s, but where we going to find a duck and a hose at this hour?'),
(3, 'Well, I think so %s, but burlap chafes me so.'),
(4, 'I think so %s, but this time you put the trousers on the chimp.'),
(5, 'I think so %s, but this time you wear the tutu.'),
(6, 'I think so %s, but me and Pipi Longstocking, I mean, what would the children look like?'),
(7, 'Well, I think so %s, but if we didn''t have ears, we''d look like weasels.'),
(8, 'Wuh, I think so %s, but isn''t Regis Philbin already married?'),
(9, 'Uh ... yeah, %s, but where are we going to find rubber pants our size?'),
(10, 'I think so, but where will we find an open tattoo parlor at this time of night?'),
(11, 'I think so %s, but culottes have a tendency to ride up so.'),
(12, 'Wuh, I think so, but we''ll never get a monkey to use dental floss.'),
(13, 'I think so %s, but if they called them ''sad meals'', kids wouldn''t buy them.'),
(14, 'Well, I think so %s, but I can''t memorize a whole opera in Yiddish.'),
(15, 'Aww, I think so, %s, but balancing a family and a career ... uh, it''s all too much for me.'),
(16, 'I think so %s, but there''s still a bug in there from last time.'),
(17, 'I think so %s, but I get all clammy inside the tent. '),
(18, 'I think so %s, but I don''t think Kay Ballard is in the union?'),
(19, 'I think so %s, but the Rockettes? I mean, it''s mostly girls, isn''t it?'),
(20, 'I think so %s, but pants with horizontal stripes makes me look chubby.'),
(21, 'Well, I think so %s, but pantyhose are so uncomfortable in the summertime.'),
(22, 'I think so %s, but it''s a miracle this one grew back.'),
(23, 'Well, I think so %s but first you''d have to take that whole bridge apart wouldn''t you?'),
(24, 'I think so, %s, but ''Snowball for Windows''?'),
(25, 'Well, I think so %s, but ''apply North Pole'' to what?'),
(26, 'I think so %s, but, snort, no, no, it''s too stupid.'),
(27, 'Umm, I think so %s, but umm, why would Sophia Loren do a musical?'),
(28, 'Umm, I think so %s, but what if the chicken won''t wear the nylons?'),
(29, 'I think so %s, but isn''t that why they invented tube socks?'),
(30, 'I think so %s but what if we stick to the seat covers?'),
(31, 'Ewww, I think so %s, but I think I''d rather eat the Macarena.'),
(32, 'I think so %s, but don''t we need a pool to play Marco Polo?'),
(33, 'Well, I think so, but Kevin Costner with an English accent?'),
(34, 'Well, I think so %s, but do I really need two tongues?'),
(35, 'We eat the box?'),
(36, 'I think so %s, but don''t camels spit a lot?'),
(37, 'I think so %s, but Pete Rose? I mean, can we trust him?'),
(38, 'I think so %s, but how do we get a pair of Abe Vegoda''s pants?'),
(39, 'I think so %s, but why would Peter Bogdanovich?'),
(40, 'Well, I think so %s, but if Jimmy cracks corn and no one cares, why does he keep doing it?'),
(41, 'I think so %s, but isn''t a cucumber that small called a gerkin?'),
(42, 'I think so %s, but if we had a snowmobile, wouldn''t it melt before summer?'),
(43, 'I think so %s, but how we will get all seven dwarves to shave their legs?'),
(44, 'I think so %s, but how do we get the Spice Girls into the paella?'),
(45, 'I think so %s, but if we get Sam spayed, he''ll never have any puppies.'),
(46, 'Well, I think so %s, but wouldn''t anything lose its flavor on the bedpost overnight?'),
(47, 'I think so %s, but three round meals a day wouldn''t be as hard to swallow.'),
(48, 'But calling it Pu-Pu platter? What were they thinking?'),
(49, 'I think so %s, but if we give peas a chance, won''t the lima beans feel left out?'),
(50, 'I think so %s, but if the plural of mouse is mice, wouldn''t the plural of spouse be spice?'),
(51, 'I think so %s, but can the gummi worms really live in peace with the Marshmellow Chicks?'),
(52, 'Yes %s, but if our knees bent the other way, how would we ride a bicycle?'),
(53, 'Yes, but why does the chicken cross the road, huh, if not for love? Oh, I don''t know.'),
(54, 'I think so %s, but I prefer space jelly.'),
(55, 'I think so %s, but why would anyone want a depressed tongue?'),
(56, 'I think so %s, but who wants to see Snow White and the Seven Samuri?'),
(57, 'I think so %s, but then my name would be ''thumby''.'),
(58, 'I think so %s, but I find scratching just makes it worse.'),
(59, 'I think so %s, but shouldn''t the bat boy be wearing a cape.'),
(60, 'Umm, I think so %s, but why would anyone want to Pierce Brosnan?'),
(61, 'Me thinks so %s, verily, but doest thou think Pete Rose by any other name would still smell as sweaty?'),
(62, 'I think so %s, but will they let the Cranberry Duchess stay in the Lincoln Bedroon?'),
(63, 'I think so %s, but why does a forklift have to be so big if all it does is lift forks?'),
(64, 'I think so %s, but wouldn''t his movies be more suitable for children if he was named ''Jean Claude Van Darn''?'),
(65, 'I think so %s, but what if the hippopotimus won''t wear the beach thong?'),
(66, 'Whew! I''d say the odds of that are terribly slim.'),
(67, 'I think so %s, but if was only supposed to be a three hour tour, why did Howells bring all his money?'),
(68, 'I think so %s, but Zero Mostel times anything is still Zero Mostel.'),
(69, 'I think so %s, but if we have nothing to fear but fear itself, then why does Elenor Roosevelt wear that spooky mask?'),
(70, 'Umm, I think so Big %s Fish Face Stove Pipe Wiggle Room Eileen. but if you get a long little doggie, wouldn''t you just call it a dachshund?'),
(71, 'I think so %s, but then I''d have to know what pondering is, wouldn''t I?'),
(72, 'I think so %s, but ''instant karma'' always gets so lumpy.'),
(73, 'Umm, I think so %s, but a show about two talking lab mice? It''ll never get on the air!');

CREATE TABLE IF NOT EXISTS `bad_words` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `word` char(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `word` (`word`)
) DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `box_of_doom` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `difficulty` enum('easy','average','hard') NOT NULL,
  `challenge` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) DEFAULT CHARSET=utf8;

INSERT INTO `box_of_doom` (`id`, `difficulty`, `challenge`) VALUES
(NULL, 'easy', '15'),
(NULL, 'easy', '17.5'),
(NULL, 'easy', '20'),
(NULL, 'easy', '22.5'),
(NULL, 'easy', '25'),
(NULL, 'easy', '27.5'),
(NULL, 'easy', '30'),
(NULL, 'easy', '32.5'),
(NULL, 'average', '27.5'),
(NULL, 'average', '30'),
(NULL, 'average', '32.5'),
(NULL, 'average', '35'),
(NULL, 'average', '37.5'),
(NULL, 'average', '40'),
(NULL, 'average', '42.5'),
(NULL, 'average', '45'),
(NULL, 'hard', '42.5'),
(NULL, 'hard', '45'),
(NULL, 'hard', '47.5'),
(NULL, 'hard', '50'),
(NULL, 'hard', '52.5'),
(NULL, 'hard', '55'),
(NULL, 'hard', '57.5'),
(NULL, 'hard', '60'),
(NULL, 'hard', '62.5'),
(NULL, 'hard', '65'),
(NULL, 'hard', '67.5');

CREATE TABLE IF NOT EXISTS `challenges` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `challenge` varchar(300) NOT NULL,
  `approved` tinyint(1) NOT NULL,
  PRIMARY KEY (`id`)
) DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `channels` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `channel` varchar(255) NOT NULL,
  `adult` tinyint(1) NOT NULL,
  `markhov` tinyint(1) NOT NULL,
  `random` tinyint(1) NOT NULL,
  `command` tinyint(1) NOT NULL,
  `relaytwitter` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`)
) DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `colours` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `string` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) DEFAULT CHARSET=utf8;

INSERT INTO `colours` (`id`, `string`) VALUES
(1, 'avocado green'),
(2, 'powder blue'),
(3, 'pale yellow'),
(4, 'sienna'),
(5, 'crimson'),
(6, 'lime green'),
(7, 'fushia'),
(8, 'orangeish yellow'),
(9, 'neon pink'),
(10, 'topaz'),
(11, 'taupe'),
(12, 'silver'),
(13, 'anguish'),
(14, 'teal'),
(15, 'aqua'),
(16, 'purple'),
(17, 'beige'),
(18, 'burgundy'),
(19, 'scarlet'),
(20, 'navy'),
(21, 'turquoise'),
(22, 'cerulean'),
(23, 'olive'),
(24, 'black'),
(25, 'chocolate'),
(26, 'beige'),
(27, 'invisible'),
(28, 'witchling'),
(29, 'maroon'),
(30, '#BBC401'),
(31, 'oxide of chromium'),
(32, 'aubergine'),
(33, 'harvest gold'),
(34, 'sparkly vampire'),
(35, 'denim'),
(36, 'dirty yellow'),
(37, 'desert'),
(38, 'dessert'),
(39, 'dirt'),
(40, '#8F223B'),
(41, 'cinnamon'),
(42, 'chrome'),
(43, 'leopard'),
(44, 'forest pink'),
(45, 'black'),
(46, 'blacker'),
(47, 'blackest'),
(48, 'poison'),
(49, 'Japan');

CREATE TABLE IF NOT EXISTS `commandments` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `string` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) DEFAULT CHARSET=utf8;

INSERT INTO `commandments` (`id`, `string`) VALUES
(1, '1. Thou shalt not edit during the Holy Months.'),
(2, '2. Thou shalt daily offer up at least 1,667 words to the altar of Chris Baty.'),
(3, '3. Keep thou holy the first and last days of the Holy Months, which are April and November.'),
(4, '4. Take not the name of Chris Baty in vain, unless it doth provide thee with greater word count, which is good.'),
(5, '5. Worry not about the quality of thy words, for Chris Baty cares not. Quantity is that which pleases Baty.'),
(6, '6. Thou must tell others of the way of the truth, by leading by example in your region.'),
(7, '7. Honor thou those who sacrifice their time. They are known as MLs and Staff members, and they are blessed.'),
(8, '8. Once in your life, ye shall make a pilgrimage to NOWD to honor thine Chris Baty'),
(9, '9. Those that sacrifice their money shall be blessed with gold, which shall be a sign unto others.'),
(10, '10. <<WRITE THIS LATER>>'),
(11, '11. Thou shalt back up thy writing often, for it is displeasing in the eyes of Baty that you should lose it.'),
(12, '12. No narrative? No botheration!');

CREATE TABLE IF NOT EXISTS `dances` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) DEFAULT CHARSET=utf8;

INSERT INTO `dances` (`id`, `name`) VALUES
(NULL, 'Agadoo'),
(NULL, 'The Alligator'),
(NULL, 'Algorithm March'),
(NULL, 'Batusi'),
(NULL, 'Bomba'),
(NULL, 'The Bump'),
(NULL, 'Bunny Hop'),
(NULL, 'The Cabbage Patch'),
(NULL, 'Carioca'),
(NULL, 'The Carlton Dance'),
(NULL, 'Cha Cha Slide'),
(NULL, 'Chicken Dance'),
(NULL, 'The Chicken Walk'),
(NULL, 'Chicken Noodle Soup'),
(NULL, 'Cotton-Eyed Joe'),
(NULL, 'Crank That'),
(NULL, 'The Creep'),
(NULL, 'Cupid Shuffle'),
(NULL, 'Do the Bartman'),
(NULL, 'Dougie'),
(NULL, 'Electric Slide'),
(NULL, 'The Fly'),
(NULL, 'The Freddy'),
(NULL, 'The Frug'),
(NULL, 'The Grizzly Bear'),
(NULL, 'Gangnam Style'),
(NULL, 'The Hammer'),
(NULL, 'Hitch hike'),
(NULL, 'Hokey Pokey'),
(NULL, 'Hully Gully'),
(NULL, 'The Humpty Dance'),
(NULL, 'The Hunch'),
(NULL, 'Hustle'),
(NULL, 'Jerk'),
(NULL, 'Jerkin'''),
(NULL, 'Jump On It'),
(NULL, 'The Ketchup Song'),
(NULL, 'Laffy Taffy'),
(NULL, 'Lambada'),
(NULL, 'Lean Back'),
(NULL, 'Snap Dance'),
(NULL, 'Letkajenkka'),
(NULL, 'Limbo'),
(NULL, 'The Loco-Motion'),
(NULL, 'Locomia'),
(NULL, 'Macarena'),
(NULL, 'Mashed Potato'),
(NULL, 'Madison'),
(NULL, 'The Meatstick'),
(NULL, 'Monkey'),
(NULL, 'The Moonwalk'),
(NULL, 'Muscle'),
(NULL, 'Nutbush City Limits'),
(NULL, 'Oops Upside Your Head'),
(NULL, 'Peanut Butter Jelly Time'),
(NULL, 'Pee-wee Herman dance'),
(NULL, 'Pony'),
(NULL, 'The Roger Rabbit'),
(NULL, 'The Running Man'),
(NULL, 'The Safety Dance'),
(NULL, 'Saturday Night'),
(NULL, 'Shimmy'),
(NULL, 'Shoulder Lean'),
(NULL, 'Single Ladies'),
(NULL, 'The Smurf'),
(NULL, 'Stanky Leg'),
(NULL, 'Suzie Q'),
(NULL, 'Thizzle Dance'),
(NULL, 'Thunder Clap'),
(NULL, 'Time Warp'),
(NULL, 'Tragedy'),
(NULL, 'The Twist'),
(NULL, 'The Urkel'),
(NULL, 'Voguing'),
(NULL, 'Walk It Out'),
(NULL, 'The Wobble'),
(NULL, 'Watusi'),
(NULL, 'YMCA'),
(NULL, 'Cozy Jig');

CREATE TABLE IF NOT EXISTS `deities` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `string` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) DEFAULT CHARSET=utf8;

INSERT INTO `deities` (`id`, `string`) VALUES
(1, 'Agdistis'),
(2, 'Ah Puch'),
(3, 'Ahura Mazda'),
(4, 'Alberich'),
(5, 'Allah'),
(6, 'Amaterasu'),
(7, 'An'),
(8, 'Anansi'),
(9, 'Anat'),
(10, 'Andvari'),
(11, 'Anshar'),
(12, 'Anu'),
(13, 'Aphrodite'),
(14, 'Apollo'),
(15, 'Apsu'),
(16, 'Ares'),
(17, 'Artemis'),
(18, 'Asclepius'),
(19, 'Athena'),
(20, 'Athirat'),
(21, 'Athtart'),
(22, 'Atlas'),
(23, 'Baal'),
(24, 'Ba Xian'),
(25, 'Bacchus'),
(26, 'Balder'),
(27, 'Bast'),
(28, 'Bellona'),
(29, 'Bergelmir'),
(30, 'Bes'),
(31, 'Bixia Yuanjin'),
(32, 'Bragi'),
(33, 'Brahma'),
(34, 'Brigit'),
(35, 'Camaxtli'),
(36, 'Ceres'),
(37, 'Ceridwen'),
(38, 'Cernunnos'),
(39, 'Chac'),
(40, 'Chalchiuhtlicue'),
(41, 'Charun'),
(42, 'Chemosh'),
(43, 'Cheng-huang'),
(44, 'Cybele'),
(45, 'Dagon'),
(46, 'Damkina'),
(47, 'Davlin'),
(48, 'Dawn'),
(49, 'Demeter'),
(50, 'Diana'),
(51, 'Di Cang'),
(52, 'Dionysus'),
(53, 'Ea'),
(54, 'El'),
(55, 'Enki'),
(56, 'Enlil'),
(57, 'Eos'),
(58, 'Epona'),
(59, 'Ereskigal'),
(60, 'Farbauti'),
(61, 'Fenrir'),
(62, 'Forseti'),
(63, 'Fortuna'),
(64, 'Freya'),
(65, 'Freyr'),
(66, 'Frigg'),
(67, 'Gaia'),
(68, 'Ganesha'),
(69, 'Ganga'),
(70, 'Garuda'),
(71, 'Gauri'),
(72, 'Geb'),
(73, 'Geong Si'),
(74, 'Guanyin'),
(75, 'Hades'),
(76, 'Hanuman'),
(77, 'Hathor'),
(78, 'Hecate'),
(79, 'Helios'),
(80, 'Heng-o'),
(81, 'Hephaestus'),
(82, 'Hera'),
(83, 'Hermes'),
(84, 'Hestia'),
(85, 'Hod'),
(86, 'Hoderi'),
(87, 'Hoori'),
(88, 'Horus'),
(89, 'Hotei'),
(90, 'Huitzilopochtli'),
(91, 'Hsi-Wang-Mu'),
(92, 'Hygeia'),
(93, 'Inanna'),
(94, 'Inti'),
(95, 'Iris'),
(96, 'Ishtar'),
(97, 'Isis'),
(98, 'Ixtab'),
(99, 'Izanaki'),
(100, 'Izanami'),
(101, 'Jesus'),
(102, 'Juno'),
(103, 'Jupiter'),
(104, 'Juturna'),
(105, 'Kagutsuchi'),
(106, 'Kartikeya'),
(107, 'Khepri'),
(108, 'Ki'),
(109, 'Kingu'),
(110, 'Kinich Ahau'),
(111, 'Kishar'),
(112, 'Krishna'),
(113, 'Kuan-yin'),
(114, 'Kukulcan'),
(115, 'Kvasir'),
(116, 'Lakshmi'),
(117, 'Leto'),
(118, 'Liza'),
(119, 'Loki'),
(120, 'Lugh'),
(121, 'Luna'),
(122, 'Magna Mater'),
(123, 'Maia'),
(124, 'Marduk'),
(125, 'Mars'),
(126, 'Mazu'),
(127, 'Medb'),
(128, 'Mercury'),
(129, 'Mimir'),
(130, 'Min'),
(131, 'Minerva'),
(132, 'Mithras'),
(133, 'Morrigan'),
(134, 'Mot'),
(135, 'Mummu'),
(136, 'Muses'),
(137, 'Nammu'),
(138, 'Nanna'),
(139, 'Nanse'),
(140, 'Neith'),
(141, 'Nemesis'),
(142, 'Nephthys'),
(143, 'Neptune'),
(144, 'Nergal'),
(145, 'Ninazu'),
(146, 'Ninhurzag'),
(147, 'Nintu'),
(148, 'Ninurta'),
(149, 'Njord'),
(150, 'Nugua'),
(151, 'Nut'),
(152, 'Odin'),
(153, 'Ohkuninushi'),
(154, 'Ohyamatsumi'),
(155, 'Orgelmir'),
(156, 'Osiris'),
(157, 'Ostara'),
(158, 'Pan'),
(159, 'Parvati'),
(160, 'Phaethon'),
(161, 'Phoebe'),
(162, 'Phoebus Apollo'),
(163, 'Pilumnus'),
(164, 'Poseidon'),
(165, 'Quetzalcoatl'),
(166, 'Rama'),
(167, 'Re'),
(168, 'Rhea'),
(169, 'Sabazius'),
(170, 'Sarasvati'),
(171, 'Selene'),
(172, 'Shiva'),
(173, 'Seshat'),
(174, 'Set'),
(175, 'Shamash'),
(176, 'Shapsu'),
(177, 'Shen Yi'),
(178, 'Shiva'),
(179, 'Shu'),
(180, 'Si-Wang-Mu'),
(181, 'Sin'),
(182, 'Sirona'),
(183, 'Sol'),
(184, 'Surya'),
(185, 'Susanoh'),
(186, 'Tawaret'),
(187, 'Tefnut'),
(188, 'Tezcatlipoca'),
(189, 'Thanatos'),
(190, 'Thor'),
(191, 'Thoth'),
(192, 'Tiamat'),
(193, 'Tianhou'),
(194, 'Tlaloc'),
(195, 'Tonatiuh'),
(196, 'Toyo-Uke-Bime'),
(197, 'Tyche'),
(198, 'Tyr'),
(199, 'Utu'),
(200, 'Uzume'),
(201, 'Vediovis'),
(202, 'Venus'),
(203, 'Vesta'),
(204, 'Vishnu'),
(205, 'Volturnus'),
(206, 'Vulcan'),
(207, 'Xipe'),
(208, 'Xi Wang-mu'),
(209, 'Xochipilli'),
(210, 'Xochiquetzal'),
(211, 'Yam'),
(212, 'Yarikh'),
(213, 'Yhwh'),
(214, 'Ymir'),
(215, 'Yu-huang'),
(216, 'Yum Kimil'),
(217, 'Zeus'),
(218, 'Chris Baty'),
(219, 'Cthulu'),
(220, 'Barney'),
(221, 'himself'),
(222, 'Utoxin'),
(223, 'his evil twin'),
(224, 'his better half'),
(225, 'Sailor Moon'),
(226, 'The Nothing'),
(227, 'Arhu'),
(228, 'Falcor'),
(229, '... You don\'t want to know.'),
(230, 'MysteriousAges');

CREATE TABLE IF NOT EXISTS `eightballs` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `string` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) DEFAULT CHARSET=utf8;

INSERT INTO `eightballs` (`id`, `string`) VALUES
(1, 'Direction unclear'),
(2, 'Yes'),
(3, 'No'),
(4, 'Maybe, if you wiggle it a bit'),
(5, 'It depends'),
(6, 'Sometimes'),
(7, 'Ask later'),
(8, 'Absolutely'),
(9, 'Porcupine'),
(10, 'Captain Picard is not aboard the Enterprise'),
(11, 'Probably'),
(12, 'I think so'),
(13, 'It may be difficult'),
(14, 'No problem'),
(15, 'You have nothing to fear'),
(16, 'It is assured'),
(17, 'Have you tried hitting it?'),
(18, 'Maybe'),
(19, 'Yes'),
(20, 'Absolutely'),
(21, 'No'),
(22, 'Never'),
(23, 'Not in a million years'),
(24, 'I''m sure of it'),
(25, 'Answer unclear'),
(26, 'Try again later'),
(27, 'Ask me again tomorrow'),
(28, 'No, you!'),
(29, 'That''s what she said'),
(30, 'Only if you hop on one foot and sing a song'),
(31, 'Have a drink and ask again'),
(32, 'Get me a drink and ask again'),
(33, 'Indubidably'),
(34, 'What, you never just want to say hi?'),
(35, 'Never in your wildest dreams'),
(36, 'Only in your wildest dreams'),
(37, 'HAHAHAHAHAHAHAHAhahahaaa...  haahaaa...  phew...  Oh yeah, totally do it.'),
(38, 'You''re joking!'),
(39, 'What even is that?'),
(40, 'Penguins'),
(41, 'Ninjas'),
(42, 'Zombies'),
(43, 'Pirates'),
(44, 'Robots'),
(45, 'Throw a fridge at something'),
(46, 'The power of Baty compels you!'),
(47, 'Chris Baty wills it.'),
(48, 'Stop shaking me!'),
(49, 'Don''t touch me there!'),
(50, 'I need a RESPONSIBLE adult!'),
(51, 'As I see it, yes'),
(52, 'It is certain'),
(53, 'It is decidedly so'),
(54, 'Most likely'),
(55, 'Outlook good'),
(56, 'Signs point to yes'),
(57, 'Without a doubt'),
(58, 'You may rely on it'),
(59, 'Better not tell you now'),
(60, 'Concetrate, and ask again'),
(61, 'Very doubtful'),
(62, 'Of course! Wait... what did I just agree to?'),
(63, 'Ye... er, I mean no'),
(64, 'Absolutely! Not.'),
(65, 'Why would you even ASK that?'),
(66, 'All your base are belong to me'),
(67, 'No. I mean Yes. Yes!'),
(68, 'The answer to your question lies in your heart. Please tell it to stop - lying is bad for your cholesterol.'),
(69, 'Have you tried sidling up to your problem?'),
(70, 'I didn''t understand the question.'),
(71, 'YA RLY'),
(72, '42'),
(73, '101010');

CREATE TABLE IF NOT EXISTS `extra_greetings` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `string` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) DEFAULT CHARSET=utf8;

INSERT INTO `extra_greetings` (`id`, `string`) VALUES
(NULL, 'Welcome to the Congregation of Chris T. Baty!'),
(NULL, 'Have you backed up your writing today?'),
(NULL, 'Have you thanked an ML or Staff member recently?'),
(NULL, 'Have you donated yet this year?'),
(NULL, 'Fact: Donators are more likely to win.'),
(NULL, 'I just lost The Game.');

CREATE TABLE IF NOT EXISTS `flavours` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `string` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) DEFAULT CHARSET=utf8;

INSERT INTO `flavours` (`id`, `string`) VALUES
(1, 'peach fudge'),
(2, 'juniper'),
(3, 'vanilla'),
(4, 'blue'),
(5, 'angry buffalo'),
(6, 'coffe'),
(7, 'insanity-covered squid'),
(8, 'white pen'),
(9, 'fried chicken'),
(10, 'peppermint chocolate'),
(11, 'crab apple'),
(12, 'pine needles'),
(13, 'mashed porkchops'),
(14, 'torment'),
(15, 'lightbulb'),
(16, 'silicon dioxide'),
(17, 'arsenic'),
(18, 'almonds'),
(19, 'strontium-237'),
(20, 'Popplers'),
(21, 'a little-endian unsigned 42'),
(22, 'pudding'),
(23, 'Nanaimo bars'),
(24, 'toffee'),
(25, 'farts'),
(26, 'rubber bands'),
(27, 'hilarity'),
(28, 'mould... have you gone bad?'),
(29, 'MattKinsi'),
(30, 'dasies'),
(31, 'squid-covered insanity'),
(32, 'GLaDOS... I should call her sometime'),
(33, 'inspiration'),
(34, 'stagnation'),
(35, 'word-padding'),
(36, 'lemon'),
(37, 'a slice of lemon wrapped ''round a large gold brick'),
(38, 'almost, but not quite, entirely unlike tea'),
(39, 'orange sorbet'),
(40, 'orange pekoe'),
(41, 'licorice'),
(42, 'cherry chocolate lemons');

CREATE TABLE IF NOT EXISTS `greetings` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `string` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) DEFAULT CHARSET=utf8;

INSERT INTO `greetings` (`id`, `string`) VALUES
(NULL, 'Grüß Gott, %s!'),
(NULL, 'Zdraveite, %s!'),
(NULL, 'Dobar dan, %s!'),
(NULL, 'Nazdar, %s!'),
(NULL, 'Goddag, %s!'),
(NULL, 'Goedendag, %s!'),
(NULL, 'Hello, %s!'),
(NULL, 'Tere päevast, %s!'),
(NULL, 'Hyvää päivää, %s!'),
(NULL, 'Bonjour, %s!'),
(NULL, 'Guten Tag, %s!'),
(NULL, 'Kalimera, %s!'),
(NULL, 'Aloha, %s!'),
(NULL, 'Shalom, %s!'),
(NULL, 'Namaste, %s!'),
(NULL, 'Szia, %s!'),
(NULL, 'Góðan dag, %s!'),
(NULL, 'Selamat pagi, %s!'),
(NULL, 'Dia duit, %s!'),
(NULL, 'Buon giorno, %s!'),
(NULL, 'Konnichiwa, %s!'),
(NULL, 'An-nyong Ha-se-yo, %s!'),
(NULL, 'Labdien, %s!'),
(NULL, 'Laba diena, %s!'),
(NULL, 'Moïen, %s!'),
(NULL, 'Selamat datang, %s!'),
(NULL, 'Merhba, %s!'),
(NULL, 'Ni hao, %s!'),
(NULL, 'Kia ora, %s!'),
(NULL, 'Hallo, %s!'),
(NULL, 'Dzien dobry, %s!'),
(NULL, 'Olá, %s!'),
(NULL, 'Bunã ziua, %s!'),
(NULL, 'Zdravstvuyte, %s!'),
(NULL, 'Hola, %s!'),
(NULL, 'God dag, %s!'),
(NULL, 'Grüzi, %s!'),
(NULL, 'Magandang tanghali po, %s!'),
(NULL, 'Li-ho, %s!'),
(NULL, 'Merhaba, %s!'),
(NULL, 'Shwmae, %s!');

CREATE TABLE IF NOT EXISTS `ignores` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `items` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `item` varchar(300) NOT NULL,
  `approved` tinyint(1) NOT NULL,
  PRIMARY KEY  (`id`)
) DEFAULT CHARSET=latin1;

INSERT INTO `items` (`id`, `item`, `approved`) VALUES
(1, 'a spork', 1),
(2, 'a freshly brewed cup of coffee', 1),
(3, 'a double chocolate cookie', 1),
(4, 'a fresh cup of confetti', 1),
(5, 'a mini-bar fridge', 1),
(6, 'an apple', 1),
(7, 'a banana peel', 1),
(8, 'tea. Earl Grey. Hot.', 1),
(9, 'androids with plungers', 1),
(10, 'a box that is bigger on the inside', 1);

CREATE TABLE IF NOT EXISTS `markhov_emote_data` (
  `first` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `second` varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `count` bigint(20) unsigned NOT NULL,
  PRIMARY KEY (`first`,`second`),
  KEY `word_count` (`first`,`count`)
) DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `markhov_say_data` (
  `first` char(100) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `second` char(100) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  `count` bigint(20) unsigned NOT NULL,
  PRIMARY KEY (`first`,`second`),
  KEY `word_count` (`first`,`count`)
) DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `settings` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `key` varchar(255) NOT NULL,
  `value` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) DEFAULT CHARSET=utf8;

INSERT INTO `settings` (`id`, `key`, `value`) VALUES
(1, 'server', 'irc.example.net'),
(2, 'nickname', 'Timmy'),
(3, 'password', ''),
(4, 'backup_nickname', 'Warmech'),
(5, 'backup_password', '');

CREATE TABLE IF NOT EXISTS `songs` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) DEFAULT CHARSET=utf8;

INSERT INTO `songs` (`id`, `name`) VALUES
(NULL, 'Foxy Doubts'),
(NULL, 'No Such Things As Accusations'),
(NULL, 'Epic Blessings'),
(NULL, 'California Junk'),
(NULL, 'Drowsy Madman'),
(NULL, 'Forget The Risks'),
(NULL, 'Ability Is Fun'),
(NULL, 'Secrets Of The Explosion'),
(NULL, 'Whip Me Up Some Scandal'),
(NULL, 'Illegal Mistakes'),
(NULL, 'Check Out The Rainbow'),
(NULL, 'Envy Don''t Cost A Penny'),
(NULL, 'Holy Fantasies'),
(NULL, 'Drowsy Twister'),
(NULL, 'Jet Fueled Ambition'),
(NULL, 'Giant Confusion'),
(NULL, 'Just Another Bunch Of Losses'),
(NULL, 'Burning Sell Out'),
(NULL, 'Trust Will Lead The Way'),
(NULL, 'Introvert Skill'),
(NULL, 'Mad Rules'),
(NULL, 'Loose Interference'),
(NULL, 'Bag Of Illusions'),
(NULL, 'Explosive Intentions'),
(NULL, 'Turning My Back On Persuasion'),
(NULL, 'Death Of The Loneliness'),
(NULL, 'Symptoms Are Ringing In My Ears'),
(NULL, 'How Many More Lyrics'),
(NULL, 'The New Face Of War'),
(NULL, 'Automatic Diversity'),
(NULL, 'Illusion Is The In-Thing'),
(NULL, 'Whats Left Of Friendship'),
(NULL, 'Pacific Limo'),
(NULL, 'Whispering Mojo'),
(NULL, '10 Things You Didn''t Know About Guilt'),
(NULL, 'Forgotten Car'),
(NULL, 'Unbelievable Storm'),
(NULL, 'Silent Crusade'),
(NULL, 'Sick Smart Mouth'),
(NULL, 'Can Of Demands'),
(NULL, 'Day Of The Tears'),
(NULL, 'Hands Off My Sweatshirt'),
(NULL, 'Friendship Remixed'),
(NULL, 'Information Confessions'),
(NULL, 'Thoughts On The Run'),
(NULL, 'Running Out Of Destiny'),
(NULL, 'Rampant Urges'),
(NULL, 'Whispering Crusade'),
(NULL, 'Potent Shadow');

CREATE TABLE IF NOT EXISTS `story` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `string` text NOT NULL,
  `author` varchar(255) NOT NULL,
  `created` datetime NOT NULL,
  PRIMARY KEY (`id`)
) DEFAULT CHARSET=utf8;
