-- Add bad pairs
-- depends: 20210729_01_dGwId-init-markov-words

INSERT INTO `alternate_pairs` (`id`, `word_one`, `word_two`)
VALUES (31, 'aww', 'noodles'),
       (2, 'banana', 'shenanigans'),
       (3, 'barbara', 'streisand'),
       (7, 'ceasar\'s', 'ghost'),
       (13, 'cheese', 'whiz'),
       (9, 'dang', 'rabbit'),
       (30, 'eat', 'slugs'),
       (29, 'eat', 'soap'),
       (4, 'fiddle', 'sticks'),
       (26, 'fish', 'paste'),
       (22, 'fraggle', 'rock'),
       (1, 'fudge', 'nuggets'),
       (11, 'gee', 'whilickers'),
       (12, 'gee', 'whiz'),
       (32, 'geez', 'louise'),
       (27, 'golly', 'gee'),
       (14, 'good', 'night'),
       (17, 'gosh', 'darnit'),
       (6, 'great', 'scott'),
       (18, 'holy', 'cow'),
       (19, 'horse', 'pucky'),
       (5, 'jiminy', 'crickets'),
       (10, 'jumpin\'', 'jiminy'),
       (28, 'kitty', 'whiskers'),
       (24, 'leapin\'', 'lizards'),
       (8, 'merlin\'s', 'beard'),
       (21, 'oh', 'snap'),
       (15, 'sam', 'hill'),
       (23, 'scuddle', 'butt'),
       (20, 'sufferin\'', 'succotash'),
       (25, 'tartar', 'sauce'),
       (16, 'william', 'shatner');