version: '3.5'

networks:
  internal:
    driver: bridge
    name: timmy-internal
    ipam:
      config:
        - subnet: 172.28.42.0/24
  public:
    driver: bridge
    name: timmy-public
    ipam:
      config:
        - subnet: 172.28.69.0/24

volumes:
  db-data:
    name: timmy-db-data
  anope-data:
    name: timmy-anope-data

services:
  bot:
    container_name: timmy-bot
    build:
      context: ../
      dockerfile: Dockerfile
    image: python:slim
    networks:
      - internal
      - public
    volumes:
      - type: bind
        source: ../
        target: /app/source
    depends_on:
      - database
      - anope

  database:
    container_name: timmy-db
    environment:
      - MARIADB_ROOT_PASSWORD=password
    image: mariadb:latest
    ports:
      - "3336:3306"
    networks:
      - internal
    volumes:
      - db-data:/var/lib/mysql/
      - type: bind
        source: ./database/conf.d
        target: /etc/mysql/conf.d
      - type: bind
        source: ./database/initdb.d
        target: /docker-entrypoint-initdb.d

  irc:
    container_name: timmy-irc
    image: inspircd/inspircd-docker:latest
    ports:
      - "6667:6667"
      - "6697:6697"
    networks:
      - internal
      - public
    environment:
      - INSP_SERVICES_IPADDR=timmy-anope
      - INSP_SERVICES_PASSWORD=password

  anope:
    container_name: timmy-anope
    image: anope/anope:latest
    networks:
      - internal
    environment:
      - ANOPE_UPLINK_IP=timmy-irc
      - ANOPE_UPLINK_PASSWORD=password
      - ANOPE_SERVICES_NAME=services.example.com
    volumes:
      - anope-data:/data
    depends_on:
      - irc
