CREATE DATABASE IF NOT EXISTS `timmy`;
USE `timmy`;

CREATE TABLE IF NOT EXISTS `admins` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `aypwips` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `string` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `bad_pairs` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `word_one` varchar(100) NOT NULL,
  `word_two` varchar(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `word_one` (`word_one`,`word_two`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `bad_words` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `word` char(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `word` (`word`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `box_of_doom` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `difficulty` enum('easy','average','hard') NOT NULL,
  `challenge` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `challenges` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `challenge` varchar(300) NOT NULL,
  `approved` tinyint(1) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `channels` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `channel` varchar(255) NOT NULL,
  `chatter_level` smallint(6) NOT NULL DEFAULT '1',
  `chatter_name_multiplier` smallint(5) unsigned NOT NULL DEFAULT '3',
  `tweet_bucket_max` float unsigned NOT NULL DEFAULT '10',
  `tweet_bucket_charge_rate` float unsigned NOT NULL DEFAULT '0.5',
  `auto_muzzle_wars` tinyint(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`),
  UNIQUE KEY `channel` (`channel`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `channel_chatter_settings` (
  `channel` varchar(255) NOT NULL,
  `setting` varchar(255) NOT NULL,
  `value` tinyint(1) NOT NULL,
  UNIQUE KEY `channel` (`channel`,`setting`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `channel_command_settings` (
  `channel` varchar(255) NOT NULL,
  `setting` varchar(255) NOT NULL,
  `value` tinyint(1) NOT NULL,
  UNIQUE KEY `channel` (`channel`,`setting`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `channel_twitter_feeds` (
  `channel` varchar(255) NOT NULL,
  `account` varchar(255) NOT NULL,
  UNIQUE KEY `channel` (`channel`,`account`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `colours` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `string` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `commandments` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `string` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `dances` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `deities` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `string` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `eightballs` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `string` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `extra_greetings` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `string` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `flavours` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `string` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `greetings` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `string` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `ignores` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `items` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `item` varchar(300) NOT NULL,
  `approved` tinyint(1) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `markov3_emote_data` (
  `first_id` int(10) unsigned NOT NULL,
  `second_id` int(10) unsigned NOT NULL,
  `third_id` int(10) unsigned NOT NULL,
  `count` int(10) unsigned NOT NULL,
  PRIMARY KEY (`first_id`,`second_id`,`third_id`),
  KEY `first_id` (`first_id`,`count`),
  KEY `second_id` (`second_id`),
  KEY `third_id` (`third_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `markov3_say_data` (
  `first_id` int(10) unsigned NOT NULL,
  `second_id` int(10) unsigned NOT NULL,
  `third_id` int(10) unsigned NOT NULL,
  `count` int(10) unsigned NOT NULL,
  PRIMARY KEY (`first_id`,`second_id`,`third_id`),
  KEY `first_id` (`first_id`,`count`),
  KEY `second_id` (`second_id`),
  KEY `third_id` (`third_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `markov_words` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `word` char(50) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `word` (`word`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `settings` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `key` varchar(255) NOT NULL,
  `value` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `songs` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `story` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `string` text NOT NULL,
  `author` varchar(255) NOT NULL,
  `created` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `wars` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `channel` varchar(255) NOT NULL,
  `starter` varchar(255) NOT NULL,
  `name` varchar(255) NOT NULL,
  `total_chains` int(10) unsigned NOT NULL DEFAULT '1',
  `current_chain` int(10) unsigned NOT NULL DEFAULT '1',
  `duration` int(10) unsigned NOT NULL,
  `remaining` int(10) unsigned NOT NULL,
  `time_to_start` int(10) unsigned NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8;

INSERT INTO `aypwips` (`id`, `string`) VALUES
(1, 'Sure, %s, but how are we going to find chaps our size?'),
(2, 'I think so, %s, but where we going to find a duck and a hose at this hour?'),
(3, 'Well, I think so %s, but burlap chafes me so.'),
(4, 'I think so %s, but this time you put the trousers on the chimp.'),
(5, 'I think so %s, but this time you wear the tutu.'),
(6, 'I think so %s, but me and Pipi Longstocking, I mean, what would the children look like?'),
(7, 'Well, I think so %s, but if we didn''t have ears, we''d look like weasels.'),
(8, 'Wuh, I think so %s, but isn''t Regis Philbin already married?'),
(9, 'Uh ... yeah, %s, but where are we going to find rubber pants our size?'),
(10, 'I think so, but where will we find an open tattoo parlor at this time of night?'),
(11, 'I think so %s, but culottes have a tendency to ride up so.'),
(12, 'Wuh, I think so, but we''ll never get a monkey to use dental floss.'),
(13, 'I think so %s, but if they called them ''sad meals'', kids wouldn''t buy them.'),
(14, 'Well, I think so %s, but I can''t memorize a whole opera in Yiddish.'),
(15, 'Aww, I think so, %s, but balancing a family and a career ... uh, it''s all too much for me.'),
(16, 'I think so %s, but there''s still a bug in there from last time.'),
(17, 'I think so %s, but I get all clammy inside the tent. '),
(18, 'I think so %s, but I don''t think Kay Ballard is in the union?'),
(19, 'I think so %s, but the Rockettes? I mean, it''s mostly girls, isn''t it?'),
(20, 'I think so %s, but pants with horizontal stripes makes me look chubby.'),
(21, 'Well, I think so %s, but pantyhose are so uncomfortable in the summertime.'),
(22, 'I think so %s, but it''s a miracle this one grew back.'),
(23, 'Well, I think so %s but first you''d have to take that whole bridge apart wouldn''t you?'),
(24, 'I think so, %s, but ''Snowball for Windows''?'),
(25, 'Well, I think so %s, but ''apply North Pole'' to what?'),
(26, 'I think so %s, but, snort, no, no, it''s too stupid.'),
(27, 'Umm, I think so %s, but umm, why would Sophia Loren do a musical?'),
(28, 'Umm, I think so %s, but what if the chicken won''t wear the nylons?'),
(29, 'I think so %s, but isn''t that why they invented tube socks?'),
(30, 'I think so %s but what if we stick to the seat covers?'),
(31, 'Ewww, I think so %s, but I think I''d rather eat the Macarena.'),
(32, 'I think so %s, but don''t we need a pool to play Marco Polo?'),
(33, 'Well, I think so, but Kevin Costner with an English accent?'),
(34, 'Well, I think so %s, but do I really need two tongues?'),
(35, 'We eat the box?'),
(36, 'I think so %s, but don''t camels spit a lot?'),
(37, 'I think so %s, but Pete Rose? I mean, can we trust him?'),
(38, 'I think so %s, but how do we get a pair of Abe Vegoda''s pants?'),
(39, 'I think so %s, but why would Peter Bogdanovich?'),
(40, 'Well, I think so %s, but if Jimmy cracks corn and no one cares, why does he keep doing it?'),
(41, 'I think so %s, but isn''t a cucumber that small called a gerkin?'),
(42, 'I think so %s, but if we had a snowmobile, wouldn''t it melt before summer?'),
(43, 'I think so %s, but how we will get all seven dwarves to shave their legs?'),
(44, 'I think so %s, but how do we get the Spice Girls into the paella?'),
(45, 'I think so %s, but if we get Sam spayed, he''ll never have any puppies.'),
(46, 'Well, I think so %s, but wouldn''t anything lose its flavor on the bedpost overnight?'),
(47, 'I think so %s, but three round meals a day wouldn''t be as hard to swallow.'),
(48, 'But calling it Pu-Pu platter? What were they thinking?'),
(49, 'I think so %s, but if we give peas a chance, won''t the lima beans feel left out?'),
(50, 'I think so %s, but if the plural of mouse is mice, wouldn''t the plural of spouse be spice?'),
(51, 'I think so %s, but can the gummi worms really live in peace with the Marshmellow Chicks?'),
(52, 'Yes %s, but if our knees bent the other way, how would we ride a bicycle?'),
(53, 'Yes, but why does the chicken cross the road, huh, if not for love? Oh, I don''t know.'),
(54, 'I think so %s, but I prefer space jelly.'),
(55, 'I think so %s, but why would anyone want a depressed tongue?'),
(56, 'I think so %s, but who wants to see Snow White and the Seven Samuri?'),
(57, 'I think so %s, but then my name would be ''thumby''.'),
(58, 'I think so %s, but I find scratching just makes it worse.'),
(59, 'I think so %s, but shouldn''t the bat boy be wearing a cape.'),
(60, 'Umm, I think so %s, but why would anyone want to Pierce Brosnan?'),
(61, 'Me thinks so %s, verily, but doest thou think Pete Rose by any other name would still smell as sweaty?'),
(62, 'I think so %s, but will they let the Cranberry Duchess stay in the Lincoln Bedroon?'),
(63, 'I think so %s, but why does a forklift have to be so big if all it does is lift forks?'),
(64, 'I think so %s, but wouldn''t his movies be more suitable for children if he was named ''Jean Claude Van Darn''?'),
(65, 'I think so %s, but what if the hippopotimus won''t wear the beach thong?'),
(66, 'Whew! I''d say the odds of that are terribly slim.'),
(67, 'I think so %s, but if was only supposed to be a three hour tour, why did Howells bring all his money?'),
(68, 'I think so %s, but Zero Mostel times anything is still Zero Mostel.'),
(69, 'I think so %s, but if we have nothing to fear but fear itself, then why does Elenor Roosevelt wear that spooky mask?'),
(70, 'Umm, I think so Big %s Fish Face Stove Pipe Wiggle Room Eileen. but if you get a long little doggie, wouldn''t you just call it a dachshund?'),
(71, 'I think so %s, but then I''d have to know what pondering is, wouldn''t I?'),
(72, 'I think so %s, but ''instant karma'' always gets so lumpy.'),
(73, 'Umm, I think so %s, but a show about two talking lab mice? It''ll never get on the air!');

INSERT INTO `box_of_doom` (`id`, `difficulty`, `challenge`) VALUES
(9, 'easy', '15'),
(10, 'easy', '17.5'),
(11, 'easy', '20'),
(12, 'easy', '22.5'),
(13, 'easy', '25'),
(14, 'easy', '27.5'),
(15, 'easy', '30'),
(16, 'easy', '32.5'),
(31, 'average', '27.5'),
(32, 'average', '30'),
(33, 'average', '32.5'),
(34, 'average', '35'),
(35, 'average', '37.5'),
(36, 'average', '40'),
(37, 'average', '42.5'),
(38, 'average', '45'),
(54, 'hard', '42.5'),
(55, 'hard', '45'),
(56, 'hard', '47.5'),
(57, 'hard', '50'),
(58, 'hard', '52.5'),
(59, 'hard', '55'),
(60, 'hard', '57.5'),
(61, 'hard', '60'),
(62, 'hard', '62.5'),
(63, 'hard', '65'),
(64, 'hard', '67.5');

INSERT INTO `colours` (`id`, `string`) VALUES
(1, 'avocado green'),
(2, 'powder blue'),
(3, 'pale yellow'),
(4, 'sienna'),
(5, 'crimson'),
(6, 'lime green'),
(7, 'fuchsia'),
(8, 'orangeish yellow'),
(9, 'neon pink'),
(10, 'topaz'),
(11, 'taupe'),
(12, 'silver'),
(13, 'anguish'),
(14, 'teal'),
(15, 'aqua'),
(16, 'purple'),
(17, 'beige'),
(18, 'burgundy'),
(19, 'scarlet'),
(20, 'navy'),
(21, 'turquoise'),
(22, 'cerulean'),
(23, 'olive'),
(25, 'chocolate'),
(27, 'invisible'),
(28, 'witchling'),
(29, 'maroon'),
(30, '#BBC401'),
(31, 'oxide of chromium'),
(32, 'aubergine'),
(33, 'harvest gold'),
(34, 'sparkly vampire'),
(35, 'denim'),
(36, 'dirty yellow'),
(37, 'desert'),
(38, 'dessert'),
(39, 'dirt'),
(40, '#8F223B'),
(41, 'cinnamon'),
(42, 'chrome'),
(43, 'leopard'),
(44, 'forest pink'),
(45, 'black'),
(46, 'blacker'),
(47, 'blackest'),
(48, 'poison'),
(49, 'Japan'),
(50, 'between'),
(51, 'black hole'),
(52, 'malachite'),
(53, 'gamboge'),
(54, 'fallow'),
(55, 'razzmatazz'),
(56, 'falu red'),
(57, 'arsenic'),
(58, 'feldgrau'),
(59, 'xanadu'),
(60, 'caput mortuum'),
(61, 'blood'),
(62, 'plaid'),
(63, 'xanthe'),
(64, 'carnelian'),
(65, 'fawn'),
(66, 'burlywood'),
(67, 'bisque'),
(68, 'lemon chiffon'),
(69, 'linen'),
(70, 'seashell'),
(71, 'papaya whip'),
(72, 'peach'),
(73, 'apricot'),
(74, 'melon'),
(75, 'atomic tangerine'),
(76, 'tea rose'),
(77, 'carrot orange'),
(78, 'orange peel'),
(79, 'pumpkin'),
(80, 'tomato'),
(81, 'bittersweet'),
(82, 'persimmon'),
(83, 'bittersweet shimmer'),
(84, 'Egyptian blue'),
(85, 'ultramarine'),
(86, 'resolution blue'),
(87, 'catalina blue'),
(88, 'winner'),
(89, 'ML Shirt Yellow'),
(90, 'winner'),
(91, 'ML Shirt'),
(92, 'almond toast'),
(93, 'bicycle yellow'),
(94, 'cancun sand'),
(95, 'after midnight blue'),
(96, 'fuzzy wuzzy brown'),
(97, 'high octane orange'),
(98, 'goldfish'),
(99, 'creeper'),
(100, 'sonic green'),
(101, 'purple mountain''s majesty'),
(102, 'ultra blue'),
(103, 'ultra orange'),
(104, 'unmellow yellow'),
(105, 'spanish leather'),
(106, 'willow herb'),
(107, 'twinkle'),
(108, 'wild blue yonder'),
(109, 'napalm orange');

INSERT INTO `commandments` (`id`, `string`) VALUES
(1, '1. Thou shalt not edit during the Holy Month.'),
(2, '2. Thou shalt daily offer up at least 1,667 words to the altar of Chris T. Baty.'),
(3, '3. Keep thou holy the first and last days of the Holy Month, which is November.'),
(4, '4. Take not the name of Chris T. Baty in vain, unless it doth provide thee with greater word count, which is good.'),
(5, '5. Worry not about the quality of thy words, for Chris T. Baty cares not. Quantity is that which pleases Baty.'),
(6, '6. Thou must tell others of the way of the truth, by leading by example in your region.'),
(7, '7. Honor thou those who sacrifice their time. They are known as MLs and Staff members, and they are blessed.'),
(8, '8. Once in your life, ye shall make a pilgrimage to NOWD to honor thine Chris T. Baty'),
(9, '9. Those that sacrifice their money shall be blessed with gold, which shall be a sign unto others.'),
(10, '10. <<WRITE THIS LATER>>'),
(11, '11. Thou shalt back up thy writing often, for it is displeasing in the eyes of Baty that you should lose it.'),
(12, '12. No narrative? No botheration!'),
(13, '13. Thou shalt not break the MLs.');

INSERT INTO `dances` (`id`, `name`) VALUES
(1, 'Agadoo'),
(2, 'The Alligator'),
(3, 'Algorithm March'),
(4, 'Batusi'),
(5, 'Bomba'),
(6, 'The Bump'),
(7, 'Bunny Hop'),
(8, 'The Cabbage Patch'),
(9, 'Carioca'),
(10, 'The Carlton Dance'),
(11, 'Cha Cha Slide'),
(12, 'Chicken Dance'),
(13, 'The Chicken Walk'),
(14, 'Chicken Noodle Soup'),
(15, 'Cotton-Eyed Joe'),
(16, 'Crank That'),
(17, 'The Creep'),
(18, 'Cupid Shuffle'),
(19, 'Do the Bartman'),
(20, 'Dougie'),
(21, 'Electric Slide'),
(22, 'The Fly'),
(23, 'The Freddy'),
(24, 'The Frug'),
(25, 'The Grizzly Bear'),
(26, 'Gangnam Style'),
(27, 'The Hammer'),
(28, 'Hitch hike'),
(29, 'Hokey Pokey'),
(30, 'Hully Gully'),
(31, 'The Humpty Dance'),
(32, 'The Hunch'),
(33, 'Hustle'),
(34, 'Jerk'),
(35, 'Jerkin'''),
(36, 'Jump On It'),
(37, 'The Ketchup Song'),
(38, 'Laffy Taffy'),
(39, 'Lambada'),
(40, 'Lean Back'),
(41, 'Snap Dance'),
(42, 'Letkajenkka'),
(43, 'Limbo'),
(44, 'The Loco-Motion'),
(45, 'Locomia'),
(46, 'Macarena'),
(47, 'Mashed Potato'),
(48, 'Madison'),
(49, 'The Meatstick'),
(50, 'Monkey'),
(51, 'The Moonwalk'),
(52, 'Muscle'),
(53, 'Nutbush City Limits'),
(54, 'Oops Upside Your Head'),
(55, 'Peanut Butter Jelly Time'),
(56, 'Pee-wee Herman dance'),
(57, 'Pony'),
(58, 'The Roger Rabbit'),
(59, 'The Running Man'),
(60, 'The Safety Dance'),
(61, 'Saturday Night'),
(62, 'Shimmy'),
(63, 'Shoulder Lean'),
(65, 'The Smurf'),
(66, 'Stanky Leg'),
(67, 'Suzie Q'),
(68, 'Thizzle Dance'),
(69, 'Thunder Clap'),
(70, 'Time Warp'),
(71, 'Tragedy'),
(72, 'The Twist'),
(73, 'The Urkel'),
(74, 'Voguing'),
(75, 'Walk It Out'),
(76, 'The Wobble'),
(77, 'Watusi'),
(78, 'YMCA'),
(79, 'Cozy Jig'),
(80, 'Gangnam Style');

INSERT INTO `deities` (`id`, `string`) VALUES
(1, 'Agdistis'),
(2, 'Ah Puch'),
(3, 'Ahura Mazda'),
(4, 'Alberich'),
(5, 'Allah'),
(6, 'Amaterasu'),
(7, 'An'),
(8, 'Anansi'),
(9, 'Anat'),
(10, 'Andvari'),
(11, 'Anshar'),
(12, 'Anu'),
(13, 'Aphrodite'),
(14, 'Apollo'),
(15, 'Apsu'),
(16, 'Ares'),
(17, 'Artemis'),
(18, 'Asclepius'),
(19, 'Athena'),
(20, 'Athirat'),
(21, 'Athtart'),
(22, 'Atlas'),
(23, 'Baal'),
(24, 'Ba Xian'),
(25, 'Bacchus'),
(26, 'Balder'),
(27, 'Bast'),
(28, 'Bellona'),
(29, 'Bergelmir'),
(30, 'Bes'),
(31, 'Bixia Yuanjin'),
(32, 'Bragi'),
(33, 'Brahma'),
(34, 'Brigit'),
(35, 'Camaxtli'),
(36, 'Ceres'),
(37, 'Ceridwen'),
(38, 'Cernunnos'),
(39, 'Chac'),
(40, 'Chalchiuhtlicue'),
(41, 'Charun'),
(42, 'Chemosh'),
(43, 'Cheng-huang'),
(44, 'Cybele'),
(45, 'Dagon'),
(46, 'Damkina'),
(47, 'Davlin'),
(48, 'Dawn'),
(49, 'Demeter'),
(50, 'Diana'),
(51, 'Di Cang'),
(52, 'Dionysus'),
(53, 'Ea'),
(54, 'El'),
(55, 'Enki'),
(56, 'Enlil'),
(57, 'Eos'),
(58, 'Epona'),
(59, 'Ereskigal'),
(60, 'Farbauti'),
(61, 'Fenrir'),
(62, 'Forseti'),
(63, 'Fortuna'),
(64, 'Freya'),
(65, 'Freyr'),
(66, 'Frigg'),
(67, 'Gaia'),
(68, 'Ganesha'),
(69, 'Ganga'),
(70, 'Garuda'),
(71, 'Gauri'),
(72, 'Geb'),
(73, 'Geong Si'),
(74, 'Guanyin'),
(75, 'Hades'),
(76, 'Hanuman'),
(77, 'Hathor'),
(78, 'Hecate'),
(79, 'Helios'),
(80, 'Heng-o'),
(81, 'Hephaestus'),
(82, 'Hera'),
(83, 'Hermes'),
(84, 'Hestia'),
(85, 'Hod'),
(86, 'Hoderi'),
(87, 'Hoori'),
(88, 'Horus'),
(89, 'Hotei'),
(90, 'Huitzilopochtli'),
(91, 'Hsi-Wang-Mu'),
(92, 'Hygeia'),
(93, 'Inanna'),
(94, 'Inti'),
(95, 'Iris'),
(96, 'Ishtar'),
(97, 'Isis'),
(98, 'Ixtab'),
(99, 'Izanaki'),
(100, 'Izanami'),
(101, 'Jesus'),
(102, 'Juno'),
(103, 'Jupiter'),
(104, 'Juturna'),
(105, 'Kagutsuchi'),
(106, 'Kartikeya'),
(107, 'Khepri'),
(108, 'Ki'),
(109, 'Kingu'),
(110, 'Kinich Ahau'),
(111, 'Kishar'),
(112, 'Krishna'),
(113, 'Kuan-yin'),
(114, 'Kukulcan'),
(115, 'Kvasir'),
(116, 'Lakshmi'),
(117, 'Leto'),
(118, 'Liza'),
(119, 'Loki'),
(120, 'Lugh'),
(121, 'Luna'),
(122, 'Magna Mater'),
(123, 'Maia'),
(124, 'Marduk'),
(125, 'Mars'),
(126, 'Mazu'),
(127, 'Medb'),
(128, 'Mercury'),
(129, 'Mimir'),
(130, 'Min'),
(131, 'Minerva'),
(132, 'Mithras'),
(133, 'Morrigan'),
(134, 'Mot'),
(135, 'Mummu'),
(136, 'Muses'),
(137, 'Nammu'),
(138, 'Nanna'),
(139, 'Nanse'),
(140, 'Neith'),
(141, 'Nemesis'),
(142, 'Nephthys'),
(143, 'Neptune'),
(144, 'Nergal'),
(145, 'Ninazu'),
(146, 'Ninhurzag'),
(147, 'Nintu'),
(148, 'Ninurta'),
(149, 'Njord'),
(150, 'Nugua'),
(151, 'Nut'),
(152, 'Odin'),
(153, 'Ohkuninushi'),
(154, 'Ohyamatsumi'),
(155, 'Orgelmir'),
(156, 'Osiris'),
(157, 'Ostara'),
(158, 'Pan'),
(159, 'Parvati'),
(160, 'Phaethon'),
(161, 'Phoebe'),
(162, 'Phoebus Apollo'),
(163, 'Pilumnus'),
(164, 'Poseidon'),
(165, 'Quetzalcoatl'),
(166, 'Rama'),
(167, 'Re'),
(168, 'Rhea'),
(169, 'Sabazius'),
(170, 'Sarasvati'),
(171, 'Selene'),
(172, 'Shiva'),
(173, 'Seshat'),
(174, 'Set'),
(175, 'Shamash'),
(176, 'Shapsu'),
(177, 'Shen Yi'),
(178, 'Shiva'),
(179, 'Shu'),
(180, 'Si-Wang-Mu'),
(181, 'Sin'),
(182, 'Sirona'),
(183, 'Sol'),
(184, 'Surya'),
(185, 'Susanoh'),
(186, 'Tawaret'),
(187, 'Tefnut'),
(188, 'Tezcatlipoca'),
(189, 'Thanatos'),
(190, 'Thor'),
(191, 'Thoth'),
(192, 'Tiamat'),
(193, 'Tianhou'),
(194, 'Tlaloc'),
(195, 'Tonatiuh'),
(196, 'Toyo-Uke-Bime'),
(197, 'Tyche'),
(198, 'Tyr'),
(199, 'Utu'),
(200, 'Uzume'),
(201, 'Vediovis'),
(202, 'Venus'),
(203, 'Vesta'),
(204, 'Vishnu'),
(205, 'Volturnus'),
(206, 'Vulcan'),
(207, 'Xipe'),
(208, 'Xi Wang-mu'),
(209, 'Xochipilli'),
(210, 'Xochiquetzal'),
(211, 'Yam'),
(212, 'Yarikh'),
(213, 'Yhwh'),
(214, 'Ymir'),
(215, 'Yu-huang'),
(216, 'Yum Kimil'),
(217, 'Zeus'),
(218, 'Chris T. Baty'),
(219, 'Cthulu'),
(220, 'Barney'),
(221, 'himself'),
(222, 'Utoxin'),
(223, 'Yog-Sothoth'),
(224, 'the Flying Spaghetti Monster'),
(225, 'an Invisible Pink Unicorn'),
(226, 'a clue'),
(227, 'the god of distraction');

INSERT INTO `eightballs` (`id`, `string`) VALUES
(1, 'Direction unclear'),
(2, 'Yes'),
(3, 'No'),
(4, 'Maybe, if you wiggle it a bit'),
(5, 'It depends'),
(6, 'Sometimes'),
(7, 'Ask later'),
(8, 'Absolutely'),
(9, 'Porcupine'),
(10, 'Captain Picard is not aboard the Enterprise'),
(11, 'Probably'),
(12, 'I think so'),
(13, 'It may be difficult'),
(14, 'No problem'),
(15, 'You have nothing to fear'),
(16, 'It is assured'),
(17, 'Have you tried hitting it?'),
(18, 'Maybe'),
(22, 'Never'),
(23, 'Not in a million years'),
(24, 'I''m sure of it'),
(25, 'Answer unclear'),
(26, 'Try again later'),
(27, 'Ask me again tomorrow'),
(28, 'No, you!'),
(29, 'That''s what she said'),
(30, 'Only if you hop on one foot and sing a song'),
(31, 'Have a drink and ask again'),
(32, 'Get me a drink and ask again'),
(33, 'Indubidably'),
(34, 'What, you never just want to say hi?'),
(35, 'Never in your wildest dreams'),
(36, 'Only in your wildest dreams'),
(37, 'HAHAHAHAHAHAHAHAhahahaaa...  haahaaa...  phew...  Oh yeah, totally do it.'),
(38, 'You''re joking!'),
(39, 'What even is that?'),
(40, 'Penguins'),
(41, 'Ninjas'),
(42, 'Zombies'),
(43, 'Pirates'),
(44, 'Robots'),
(45, 'Throw a fridge at something'),
(46, 'The power of Baty compels you!'),
(47, 'Chris T. Baty wills it.'),
(48, 'Stop shaking me!'),
(49, 'Don''t touch me there!'),
(50, 'I need a RESPONSIBLE adult!'),
(51, 'As I see it, yes'),
(52, 'It is certain'),
(53, 'It is decidedly so'),
(54, 'Most likely'),
(55, 'Outlook good'),
(56, 'Signs point to yes'),
(57, 'Without a doubt'),
(58, 'You may rely on it'),
(59, 'Better not tell you now'),
(60, 'Concetrate, and ask again'),
(61, 'Very doubtful'),
(62, 'Of course! Wait... what did I just agree to?'),
(63, 'Ye... er, I mean no'),
(64, 'Absolutely! Not.'),
(65, 'Why would you even ASK that?'),
(66, 'All your base are belong to me'),
(67, 'No. I mean Yes. Yes!'),
(69, 'Have you tried sidling up to your problem?'),
(70, 'I didn''t understand the question.'),
(71, 'YA RLY'),
(72, 'Your supervisor is thinking about you.'),
(73, 'May your camel be as swift as the wind.'),
(74, 'Look!  A ladder!  Maybe it leads to heaven, or a sandwich!'),
(75, 'It is much harder to find a job than to keep one.'),
(76, 'What''s another word for "thesaurus"?'),
(77, 'Keep the phase, baby.'),
(78, 'Too many interrupts'),
(79, 'The monitor needs another box of pixels.'),
(80, 'CPU needs recalibration'),
(81, 'You put the disk in upside down.'),
(82, 'I just lost The Game.'),
(83, 'The cake is a lie.'),
(84, 'There will be cake.'),
(85, '24 hour flu'),
(86, 'Adducted by aliens'),
(87, 'Amnesia'),
(88, 'Car trouble'),
(89, 'Full moon, huh?'),
(90, 'I was mugged'),
(91, 'It''s in the mail'),
(92, 'It''s not my job'),
(93, 'I''ve got a headache'),
(94, 'Jury duty'),
(95, 'Kryptonite'),
(96, 'Mexican food'),
(97, 'My dog ate it'),
(98, 'My fish died'),
(99, 'No hablo ingleses'),
(100, 'Oprah'),
(101, 'The voices told me to'),
(102, 'Traffic was bad'),
(103, 'What memo?'),
(104, 'At least I love you'),
(105, 'Brilliant idea!'),
(106, 'Half full'),
(107, 'Have you lost weight?'),
(108, 'It can''t be all that bad'),
(109, 'Look on the bright side'),
(110, 'Nice job!'),
(111, 'Nice outfit!'),
(112, 'Nice try!'),
(113, 'People like you'),
(114, 'Pure genius!'),
(115, 'That''s ok'),
(116, 'As if'),
(117, 'Ask me if I care'),
(118, 'Dumb question, ask another'),
(119, 'Forget about it'),
(120, 'Get a clue'),
(121, 'In your dreams'),
(122, 'Not'),
(123, 'Not a chance'),
(124, 'Obviously'),
(125, 'Oh please'),
(126, 'That''s ridiculous'),
(127, 'You''ve got to be kidding...'),
(128, 'This statement is false.'),
(129, 'Find the answer in my book! http://bit.ly/HdBo1Z'),
(130, 'I''m pretty sure I saw the answer to that in my book... http://bit.ly/HdBo1Z');

INSERT INTO `extra_greetings` (`id`, `string`) VALUES
(1, 'Welcome to the Congregation of Chris T. Baty!'),
(2, 'Have you backed up your writing today?'),
(3, 'Have you thanked an ML or Staff member recently?'),
(4, 'Have you donated yet this year?'),
(5, 'Fact: Donators are more likely to win.'),
(6, 'I just lost The Game.'),
(7, 'Have you hugged a chatbot today?'),
(8, 'Please report all velociraptor sightings to your local MLVSA representative!'),
(9, 'What are you getting your bot for Christmas?'),
(10, 'Have you seen the novel I wrote last year? You can buy it at these URLs: http://bit.ly/19VurZW or http://amzn.to/1bwkci6'),
(11, 'Want to help me write my 2013 novel? Add to it with !chainnew (See !help)');

INSERT INTO `flavours` (`id`, `string`) VALUES
(1, 'peach fudge'),
(2, 'juniper'),
(3, 'vanilla'),
(4, 'blue'),
(5, 'angry buffalo'),
(6, 'coffe'),
(7, 'insanity-covered squid'),
(8, 'white pen'),
(9, 'fried chicken'),
(10, 'peppermint chocolate'),
(11, 'crab apple'),
(12, 'pine needles'),
(13, 'mashed porkchops'),
(14, 'torment'),
(15, 'lightbulb'),
(16, 'silicon dioxide'),
(17, 'arsenic'),
(18, 'almonds'),
(19, 'strontium-237'),
(20, 'Popplers'),
(21, 'a little-endian unsigned 42'),
(22, 'pudding'),
(23, 'Nanaimo bars'),
(24, 'toffee'),
(25, 'farts'),
(26, 'rubber bands'),
(27, 'hilarity'),
(28, 'mould... have you gone bad?'),
(29, 'MattKinsi'),
(30, 'dasies'),
(31, 'squid-covered insanity'),
(32, 'GLaDOS... I should call her sometime'),
(33, 'inspiration'),
(34, 'stagnation'),
(35, 'word-padding'),
(36, 'lemon'),
(37, 'a slice of lemon wrapped ''round a large gold brick'),
(38, 'almost, but not quite, entirely unlike tea'),
(39, 'tea. Earl Grey. Hot.'),
(40, 'orange serbet'),
(41, 'orange pekoe'),
(42, 'licorice'),
(43, 'cherry chocolate lemons'),
(44, 'iocane powder'),
(45, 'resurrection pill');

INSERT INTO `greetings` (`id`, `string`) VALUES
(1, 'Grüß Gott, %s!'),
(2, 'Zdraveite, %s!'),
(3, 'Dobar dan, %s!'),
(4, 'Nazdar, %s!'),
(5, 'Goddag, %s!'),
(6, 'Goedendag, %s!'),
(7, 'Hello, %s!'),
(8, 'Tere päevast, %s!'),
(9, 'Hyvää päivää, %s!'),
(10, 'Bonjour, %s!'),
(11, 'Guten Tag, %s!'),
(12, 'Kalimera, %s!'),
(13, 'Aloha, %s!'),
(14, 'Shalom, %s!'),
(15, 'Namaste, %s!'),
(16, 'Szia, %s!'),
(17, 'Góðan dag, %s!'),
(18, 'Selamat pagi, %s!'),
(19, 'Dia duit, %s!'),
(20, 'Buon giorno, %s!'),
(21, 'Konnichiwa, %s!'),
(22, 'An-nyong Ha-se-yo, %s!'),
(23, 'Labdien, %s!'),
(24, 'Laba diena, %s!'),
(25, 'Moïen, %s!'),
(26, 'Selamat datang, %s!'),
(27, 'Merhba, %s!'),
(28, 'Ni hao, %s!'),
(29, 'Kia ora, %s!'),
(30, 'Hallo, %s!'),
(31, 'Dzien dobry, %s!'),
(32, 'Olá, %s!'),
(33, 'Bunã ziua, %s!'),
(34, 'Zdravstvuyte, %s!'),
(35, 'Hola, %s!'),
(36, 'God dag, %s!'),
(37, 'Grüzi, %s!'),
(38, 'Magandang tanghali po, %s!'),
(39, 'Li-ho, %s!'),
(40, 'Merhaba, %s!'),
(41, 'Shwmae, %s!'),
(42, 'Dobrý den, %s!'),
(43, 'Huthegelluthego, h-idiguh-el l-idiguh-o %s!'),
(45, 'Sawubona, %s!'),
(46, 'Ellohay, %s!'),
(47, 'Tungjatjeta, %s.'),
(49, 'Degemer mad, %s!'),
(50, 'NuqneH, %s?'),
(51, 'Kaltxì, %s.'),
(52, 'Hung-ee-lung-lung-oh, %s.');

INSERT INTO `songs` (`id`, `name`) VALUES
(1, 'Foxy Doubts'),
(3, 'No Such Things As Accusations'),
(4, 'Epic Blessings'),
(5, 'California Junk'),
(6, 'Drowsy Madman'),
(7, 'Forget The Risks'),
(8, 'Ability Is Fun'),
(9, 'Secrets Of The Explosion'),
(10, 'Whip Me Up Some Scandal'),
(11, 'Illegal Mistakes'),
(12, 'Check Out The Rainbow'),
(13, 'Envy Don''t Cost A Penny'),
(14, 'Holy Fantasies'),
(15, 'Drowsy Twister'),
(16, 'Jet Fueled Ambition'),
(17, 'Giant Confusion'),
(18, 'Just Another Bunch Of Losses'),
(19, 'Burning Sell Out'),
(20, 'Trust Will Lead The Way'),
(21, 'Introvert Skill'),
(22, 'Mad Rules'),
(23, 'Loose Interference'),
(24, 'Bag Of Illusions'),
(25, 'Explosive Intentions'),
(26, 'Turning My Back On Persuasion'),
(27, 'Death Of The Loneliness'),
(28, 'Symptoms Are Ringing In My Ears'),
(29, 'How Many More Lyrics'),
(30, 'The New Face Of War'),
(31, 'Automatic Diversity'),
(32, 'Illusion Is The In-Thing'),
(33, 'Whats Left Of Friendship'),
(34, 'Pacific Limo'),
(35, 'Whispering Mojo'),
(36, '10 Things You Didn''t Know About Guilt'),
(37, 'Forgotten Car'),
(38, 'Unbelievable Storm'),
(39, 'Silent Crusade'),
(40, 'Sick Smart Mouth'),
(41, 'Can Of Demands'),
(42, 'Day Of The Tears'),
(43, 'Hands Off My Sweatshirt'),
(44, 'Friendship Remixed'),
(45, 'Information Confessions'),
(46, 'Thoughts On The Run'),
(47, 'Running Out Of Destiny'),
(48, 'Rampant Urges'),
(49, 'Whispering Crusade'),
(50, 'Potent Shadow'),
(51, 'What Does The Fox Say?');

ALTER TABLE `channel_chatter_settings`
  ADD CONSTRAINT `channel_chatter_settings_ibfk_1` FOREIGN KEY (`channel`) REFERENCES `channels` (`channel`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `channel_command_settings`
  ADD CONSTRAINT `channel_command_settings_ibfk_1` FOREIGN KEY (`channel`) REFERENCES `channels` (`channel`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `channel_twitter_feeds`
  ADD CONSTRAINT `channel_twitter_feeds_ibfk_1` FOREIGN KEY (`channel`) REFERENCES `channels` (`channel`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `markov3_emote_data`
  ADD CONSTRAINT `markov3_emote_data_ibfk_1` FOREIGN KEY (`first_id`) REFERENCES `markov_words` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  ADD CONSTRAINT `markov3_emote_data_ibfk_2` FOREIGN KEY (`second_id`) REFERENCES `markov_words` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  ADD CONSTRAINT `markov3_emote_data_ibfk_3` FOREIGN KEY (`third_id`) REFERENCES `markov_words` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;

INSERT INTO `settings` (`key`, `value`) VALUES
('server', 'timmy-irc'),
('nickname', 'Timmy'),
('realname', 'Tim, The Enchanter'),
('backup_nickname', 'Warmech'),
('post_identify', 'OPER Timmy PASSWORD'),
('do_irc_logging', '1'),
('irc_logging_channel', '#timmy_debug'),
('auth_on_welcome', '1'),
('auth_type', 'nickserv'),
('auth_data', 'password'),
('twitter_consumer_key', ''),
('twitter_consumer_secret', ''),
('twitter_access_key', ''),
('twitter_access_secret', '');